nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'GET', 'PUT', 'DELETE', 'PATCH', 'OPTIONS']
            max_age: 3600




    #     allow_origin: ['*']         # Change this to your allowed origin URLs if needed
    #     allow_methods: ['POST', 'GET', 'PUT', 'DELETE', 'OPTIONS']  # Add other allowed methods if needed
    #     allow_headers: ['Content-Type', 'Authorization']
    #     expose_headers: []
    #     max_age: 3600
    #     hosts: []
    #     origin_regex: false
    #     forced_allow_origin_value: ~
    # paths:
    #     '^/':  # You can specify specific paths here if needed
    #         allow_origin: ['*']
    #         allow_headers: ['*']
    #         allow_methods: ['POST', 'GET', 'PUT', 'DELETE', 'OPTIONS']
    #         max_age: 3600
    #         # specify more paths if needed
